#!/bin/bash
script_path=${BASH_SOURCE[0]}
if [ -L "$script_path" ]; then
  script_path=$(readlink "$script_path")
fi
parent_path=$(dirname "$script_path")
cd "$parent_path"

source ".venv/bin/activate"
python . $@
